# Generated by Django 5.1.6 on 2025-03-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('consultation', 'Консультация'), ('social', 'Социальный')], default='social', max_length=20, verbose_name='Тип чата'),
        ),
    ]
