# Generated by Django 5.1.6 on 2025-03-31 16:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_call'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='chat_type',
        ),
        migrations.AlterField(
            model_name='call',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_call', to='chat.chat', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='call',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='call',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='call',
            name='room_url',
            field=models.URLField(verbose_name='URL комнаты'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(related_name='chats', related_query_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
