# Generated by Django 5.1.6 on 2025-04-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_chat_booking_remove_chat_chat_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='updated',
            field=models.BooleanField(default=False, verbose_name='Отредактировано'),
        ),
    ]
