# Generated by Django 5.1.4 on 2025-02-13 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
