# Generated by Django 5.1.6 on 2025-02-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/def_icon.png', null=True, upload_to='profile_pics'),
        ),
    ]
