# Generated by Django 5.1.6 on 2025-03-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='Asia/Almaty', max_length=50),
        ),
    ]
