# Generated by Django 5.1.6 on 2025-04-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover_photo',
            field=models.ImageField(blank=True, default='images/default_cover.png', null=True, upload_to='profile_pics'),
        ),
    ]
