# Generated by Django 5.1.6 on 2025-04-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover_photo',
            field=models.ImageField(blank=True, default='images/default_cover.svg', null=True, upload_to='profile_pics'),
        ),
    ]
