# Generated by Django 5.1.6 on 2025-04-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/ava.svg', null=True, upload_to='profile_pics'),
        ),
    ]
