# Generated by Django 5.1.6 on 2025-03-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='available_times',
            field=models.TextField(blank=True, help_text='Укажите удобное для вас время. Можно перечислить несколько вариантов, разделив запятыми.', null=True, verbose_name='Предпочтительные временные интервалы'),
        ),
        migrations.AddField(
            model_name='booking',
            name='problem_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время консультации'),
        ),
    ]
