# Generated by Django 5.1.6 on 2025-03-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_options_remove_booking_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
