# Generated by Django 5.1.6 on 2025-02-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, verbose_name='Специализация'),
        ),
    ]
