# Generated by Django 5.1.6 on 2025-04-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_review_delete_expertreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='specialization',
            field=models.CharField(blank=True, choices=[('developer', 'Разработчик'), ('designer', 'Дизайнер'), ('marketing', 'Маркетинг'), ('finance', 'Финансы'), ('cybersport', 'Киберспорт'), ('other', 'Другое')], max_length=255, verbose_name='Специализация'),
        ),
    ]
