# Generated by Django 5.1.6 on 2025-04-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0005_alter_expert_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='specialization',
            field=models.CharField(blank=True, choices=[('developer', 'Разработчик'), ('designer', 'Дизайнер'), ('marketing', 'Маркетинг'), ('finance', 'Финансы'), ('cybersport', 'Киберспорт'), ('other', 'Другое'), ('analyst', 'Аналитик'), ('manager', 'Менеджер'), ('programmer', 'Программист'), ('architect', 'Архитектор'), ('copywriter', 'Копирайтер'), ('psychologist', 'Психолог'), ('journalist', 'Журналист'), ('translator', 'Переводчик'), ('teacher', 'Педагог'), ('photographer', 'Фотограф'), ('web_developer', 'Веб-разработчик'), ('mobile_developer', 'Мобильный разработчик'), ('sys_admin', 'Системный администратор'), ('tester', 'Тестировщик'), ('db_admin', 'Администратор базы данных'), ('network_engineer', 'Сетевой инженер'), ('seo_specialist', 'SEO-специалист'), ('ui_ux_designer', 'UI/UX дизайнер'), ('devops_engineer', 'DevOps-инженер'), ('strategy_consultant', 'Стратегический консультант'), ('lawyer', 'Юрист'), ('doctor', 'Врач'), ('coach', 'Тренер'), ('personal_trainer', 'Персональный тренер'), ('financial_advisor', 'Финансовый консультант'), ('pr_manager', 'PR-менеджер'), ('social_worker', 'Социальный работник'), ('sales_specialist', 'Специалист по продажам'), ('content_manager', 'Контент-менеджер'), ('recruiter', 'Рекрутер')], max_length=255, verbose_name='Специализация'),
        ),
    ]
