# Generated by Django 5.1.6 on 2025-04-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0007_alter_expert_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
